end with user root, the entrypointand gosu will change it

diff --git a/docker/recipes/agilepy/Dockerfile b/docker/recipes/agilepy/Dockerfile
--- a/docker/recipes/agilepy/Dockerfile
+++ b/docker/recipes/agilepy/Dockerfile
@@ -15,6 +15,12 @@ RUN git clone --recursive https://github.com/AGILESCIENCE/Agilepy.git && \
     python3 -m pip install --no-cache-dir -r requirements.lock && \
     python3 -m pip install --no-cache-dir .
 
+# Download the test dataset, print message if it fails
+RUN if ! download_test_dataset.sh; then \
+      echo "!!! WARNING: Test dataset download failed during build." >&2; \
+      echo "    You can manually rerun it inside the container with: download_test_dataset.sh"; \
+    fi
+
 # Add Gosu for user management, Shared Directory, Entrypoint and Welcome Script
 USER root
 RUN wget -O /usr/local/bin/gosu https://github.com/tianon/gosu/releases/download/1.19/gosu-amd64 && \
@@ -26,15 +32,6 @@ RUN mkdir /shared_dir && \
     cp Agilepy/docker/recipes/agilepy/entrypoint.sh /home/flareadvocate/entrypoint.sh && \
     chmod +x /home/flareadvocate/entrypoint.sh && \
     echo "bash /home/flareadvocate/Agilepy/agilepy/scripts/welcome.sh" >> /home/flareadvocate/.bashrc
-
-# Set the user
-USER flareadvocate
-
-# Download the test dataset, print message if it fails
-RUN if ! download_test_dataset.sh; then \
-      echo "!!! WARNING: Test dataset download failed during build." >&2; \
-      echo "    You can manually rerun it inside the container with: download_test_dataset.sh"; \
-    fi
 
 # Set entrypoint
 ENTRYPOINT ["bash", "/home/flareadvocate/entrypoint.sh"]
